### ISSUE TITLE
Img2img layout modification.

### ISSUE THREAD

**Issue by Gerschel** [Nacurutu/Dark-Themes-SD-WebUI-Automatic1111#3]
Thanks for all the replies! I've switched to `--theme=dark` and again updated Quick CSS but the layout hasn't changed. Maybe I'm confused but I'm looking for this layout, 

![Alani (Small)](https://user-images.githubusercontent.com/22641919/214383855-80248b7c-7ac2-4623-aa92-02df1e856fb3.png)

Also Nacurutu, I'm getting errors in the console if I select a style and hit Apply (Reload UI) but not if I hit Apply Style, then Apply Changes (Reload UI)

_Originally posted by @BoxJockey in https://github.com/Nacurutu/Dark-Themes-SD-WebUI-Automatic1111/issues/2#issuecomment-1402444392_

**Comment by Gerschel** [comment]
I'm wondering if this was moved to the end of the settings panel, and flex was modified on 'img2img_settings' to make this as a column, would it still work.  

```javascript
let m = gradioApp().getElementById("mode_img2img")
m.parentElement.insertAdjacentElement("beforeend", m)
```

**Comment by Nacurutu** [comment]
> I'm wondering if this was moved to the end of the settings panel, and flex was modified on 'img2img_settings' to make this as a column, would it still work.
> 
> ```js
> let m = gradioApp().getElementById("mode_img2img")
> m.parentElement.insertAdjacentElement("beforeend", m)
> ```
> 
> @Nacurutu How were you moving it before?

Just using CSS, modifying the flex order and forcing some heights and widths... (that's why it doesn't worked on mobile).

```css 
*----------------------------------------------------------------*/
/* img2img tab Layout test (WORK IN PROGRESS) v2
/*----------------------------------------------------------------*/

/*Puts settings and canvas next to each other. Flex grow make entire section bigger than the gallery*/
#img2img_settings { 
  display: flex; 
  flex-direction: row-reverse;
  flex-grow: 3 !important;
}

/* img2img tabs panel no wrap*/
.dark .tabitem .overflow-hidden .overflow-hidden .flex-wrap .overflow-hidden > .flex-col > .flex-wrap{
  flex-wrap:nowrap;
 }


/*Tabs and inpainting canvas, add less flex shrink to make canvas take up more space*/
#mode_img2img {
  flex-shrink: 0.4;
}

/* img2img tabs container fixed width and height */

.dark .tabitem .overflow-hidden .overflow-hidden .flex-wrap .overflow-hidden .flex-col .tabitem{
  max-height:800px !important;
  min-height:800px !important;
 
}

.dark .min-h-screen .mx-auto .overflow-hidden #tabs .tabitem .overflow-hidden .overflow-hidden .flex-wrap .overflow-hidden .flex-col .tabitem > .overflow-hidden > .overflow-hidden{
  max-height: 780px !important;
  min-height: 780px !important;
}

.dark .min-h-screen .mx-auto .overflow-hidden #tabs .tabitem .overflow-hidden .overflow-hidden .flex-wrap .overflow-hidden .flex-col .tabitem .overflow-hidden .overflow-hidden .h-60 .cursor-pointer{
  max-height: 760px !important;
  min-height: 760px !important;
}

.dark .overflow-hidden > .overflow-hidden > .flex-wrap > .overflow-hidden > .flex-col {
  max-width: 1200px !important;
  min-width: 610px !important;
}

/* Overflow hidden */
.dark .tabitem:nth-child(3) .overflow-hidden:nth-child(1) .overflow-hidden:nth-child(3) .flex-wrap:nth-child(1) > .overflow-hidden:nth-child(2) > .overflow-hidden:nth-child(2){
  min-width:450px !important;
  max-width: 610px;
  flex-direction:column;
  align-self:center;
 }

.dark .min-h-screen .mx-auto .overflow-hidden:nth-child(1) #tabs .tabitem:nth-child(3) .overflow-hidden:nth-child(1) .overflow-hidden:nth-child(3) .flex-wrap:nth-child(1) > .overflow-hidden:nth-child(2) > .overflow-hidden:nth-child(2){
  min-width:430px !important;
 }

/* Trying to fix the Resize issue on inpainting tab */

.dark #tabs .tabitem .overflow-hidden .overflow-hidden .flex-wrap .overflow-hidden .flex-col .tabitem .overflow-hidden .overflow-hidden .h-60 .cursor-pointer .h-full .hover\:cursor-none{
  width: 100% !important;
  height:100% !important;
 }

 /* New img2img buttons reposition and border*/

 #tabs .tabitem .gr-compact{
  margin-top:18px;
  z-index: 100;
 }

 #tabs .gr-compact .gr-button-secondary{
  border-color:var(--Secondary_color);
  border-width:0.5px !important;
 }

```

**Comment by Gerschel** [comment]
Try something like this
I don't know how to say take full column, so I tried a random number for span high enough to be greater than the number of siblings, it can probably be set higher.
I used `grid-column` to say be in the second column.
`grid-template-columns` takes in a value and each value is a column, `auto auto` means two columns that automatically determine their size.
```css
#img2img_settings {
  display: grid;
  grid-template-columns: auto atuo;
}

#mode_img2img{
  grid-row: 1 / span 8;
  grid-column: 2;
}
```

**Comment by Nacurutu** [comment]
> Try something like this I don't know how to say take full column, so I tried a random number for span high enough to be greater than the number of siblings, it can probably be set higher. I used `grid-column` to say be in the second column. `grid-template-columns` takes in a value and each value is a column, `auto auto` means two columns that automatically determine their size.
> 
> ```css
> #img2img_settings {
>   display: grid;
>   grid-template-columns: auto atuo;
> }
> 
> #mode_img2img{
>   grid-row: 1 / span 8;
>   grid-column: 2;
> }
> ```

gonna try it and let u know :)

**Comment by Nacurutu** [comment]
@Gerschel 

![image](https://user-images.githubusercontent.com/18109442/214417041-da02b887-7279-4ef0-9000-ede9876a0ad6.png)

you are a genius... im so dumb for this things xD

now, need to check how to resize to cover everything, going to work on it

Thanks a lot!

**Comment by Nacurutu** [comment]
@Gerschel 

Well, I managed to do this:

![image](https://user-images.githubusercontent.com/18109442/214458506-ec8f02aa-f712-4942-859d-a7effec433af.png)


```css

/* img2img settings + mode img2img layout left to right*/
/*----------------------------------------------------------------*/
#img2img_settings {
  display: grid;
  grid-template-columns: 2.5fr 5fr;
  
}

#mode_img2img {
  grid-row: 1 / span 8;
  grid-column: 2;
}

/* Shrink Gallery*/
/*----------------------------------------------------------------*/
#img2img_gallery_container,
#img2img_gallery_container .livePreview,
#img2img_results,
#img2img_gallery{
  min-width: min(250px, 100%) !important ;
  flex-grow: 0.5 !important;
  }

/* img2img editor resize*/
/*----------------------------------------------------------------*/
  #img2img_image, 
  #img2img_image > .h-60, 
  #img2img_image > .h-60 > div, 
  #img2img_image > .h-60 > div > img,
  #img2img_sketch, 
  #img2img_sketch > .h-60, 
  #img2img_sketch > .h-60 > div, 
  #img2img_sketch > .h-60 > div > img,
  #img2maskimg, 
  #img2maskimg > .h-60, 
  #img2maskimg > .h-60 > div, 
  #img2maskimg > .h-60 > div > img,
  #inpaint_sketch, 
  #inpaint_sketch > .h-60, 
  #inpaint_sketch > .h-60 > div, 
  #inpaint_sketch > .h-60 > div > img
  {
      height: 800px !important;
      max-height: 800px !important;
      min-height: 800px !important;
 }
```

However, it has issues.

if you load an image on img2img, everything apparently looks ok, 

![image](https://user-images.githubusercontent.com/18109442/214459965-071161a3-15b1-4e07-8893-3dafaeb3bfb1.png)


But, when you add an image to the other 3 tabs (Sketch, inpaint, and inpaint sketch), the layout turns crazy. 

![image](https://user-images.githubusercontent.com/18109442/214459393-4b1f464f-1c2f-45a9-a4ea-8d99bef62411.png)

The image expand, and if, for example, after you load an image to the inpaint, change to another tab and you get back to inpaint, the img2img settings shrink...

![image](https://user-images.githubusercontent.com/18109442/214459278-fa92e888-279a-4077-8518-f39b98f37c70.png)

Also, we have the same issue where the inpaint makes the image smaller (with another same image in the background at the correct scale)

![image](https://user-images.githubusercontent.com/18109442/214459629-0073074b-3f19-4706-9f7c-bd8af77f70da.png)

Annnnnnnd, the mobile version looks awful xD.

Dont know what else to do, I have tried everything I know (not to much)

Could you try?

Copy the code to the bottom of the Alani file and test.

Thank in advance.

**Comment by Gerschel** [comment]
oops. We'll come up with something soon. I deleted my presets, still have a local copy, privatized my xyz, deleted a few other projects. Had too many projects going on, I've dealt with others' just taking my work and making themselves look good too many times. Made it not fun. I'll have more time for this project. But, just so you know, you are welcome to the quickcss to do whatever, I had a problem with people just copying it and submitting it to the main app, stole my thunder.

**Comment by Nacurutu** [comment]
> oops. We'll come up with something soon. I deleted my presets, still have a local copy, privatized my xyz, deleted a few other projects. Had too many projects going on, I've dealt with others' just taking my work and making themselves look good too many times. Made it not fun. I'll have more time for this project. But, just so you know, you are welcome to the quickcss to do whatever, I had a problem with people just copying stuff and submitting it to the main app before I could, stole my thunder.

People should, at least, mention you if they use your code.. I understand.

Thank you for letting me add my little contribution to the quickcss extension. 

Cheer up!

**Comment by Gerschel** [comment]
Your good dude, in my eyes, you have ownership of the other repo, it's your work too.

**Comment by Gerschel** [comment]
I'm putting this here for reference. It needs updating, it's an old file I was working on, but I almost lost it, so I'm dropping the contents here. The idea is to create a base template.  
```css
/*Controllers*/
root, *, quickcss_target{
    --highlight_color: #ce6400;
    --inactive_color: #4E1400;
    /*ENDCOLORPICKERS*/
    --left_column: 54;
    --font_scaler: 50;
    /*BREAKFILEREADER*/
}



/* generic html tags */
html { font-size: calc(16px / 50 * var(--font_scaler)); }
body, button, input, select, textarea { font-family: "Segoe UI"; font-variant: small-caps; }
img { background-color: black; }
input[type=range] { height: 14px; appearance: none; margin-top: 12px }
input[type=range]::-webkit-slider-runnable-track { width: 100%; height: 18px; cursor: pointer; box-shadow: 2px 2px 3px #111111; background: #50555C; border-radius: 2px; border: 0px solid #222222; }
input[type=range]::-webkit-slider-thumb { box-shadow: 2px 2px 3px #111111; border: 0px solid #000000; height: 18px; width: 40px; border-radius: 2px; background: var(--highlight_color); cursor: pointer; -webkit-appearance: none; margin-top: 0px; }
::-webkit-scrollbar { width: 12px; }
::-webkit-scrollbar-track { background: #333333; }
::-webkit-scrollbar-thumb { background-color: var(--highlight_color); border-radius: 2px; border-width: 0; box-shadow: 2px 2px 3px #111111; }

/* main gradio components by selector */
div.gradio-container.dark > div.w-full.flex.flex-col.min-h-screen > div { background-color: black; }
div.gradio-container.dark > div.w-full.flex.flex-col.min-h-screen > footer { display: none; }

/* gradio shadowroot */
.gradio-container { font-family: "Segoe UI"; font-variant: small-caps;}

/* gradio style classes */
.tabs { background-color: black; }
.dark { background-color: black; }
.dark .gr-panel { border-radius: 0; background-color: black; }
.dark .gr-input-label { color: lightyellow; border-width: 0; background: transparent; padding: 2px !important; }
.dark .gr-input { background-color: #333333 !important; }
.dark .gr-form { border-radius: 0; border-width: 0; }
.dark .gr-check-radio { background-color: var(--inactive_color); border-width: 0; border-radius: 2px; box-shadow: 2px 2px 3px #111111; }
.dark .gr-check-radio:checked { background-color: var(--highlight_color); }
.dark .gr-button { border-radius: 0; font-weight: normal; box-shadow: 2px 2px 3px #111111; font-size: calc(0.9rem / 50 * var(--font_scaler)); min-width: 32px; }
.dark .gr-box { border-radius: 0; background-color: #222222; box-shadow: 2px 2px 3px #111111; border-width: 0; padding-bottom: 12px; }
.dark .dark\:bg-gray-900 { background-color: black; }
.dark .bg-white { color: lightyellow; border-radius: 0; }
.dark fieldset span.text-gray-500, .dark .gr-block.gr-box span.text-gray-500, .dark label.block span { background-color: #222222; padding: 0 12px 0 12px; }
.dark .bg-gray-200, .dark .\!bg-gray-200 { background-color: transparent; }
.gap-2 { padding-top: 8px; }
.border-2 { border-width: 0; }
.border-b-2 { border-bottom-width: 2px; border-color: var(--highlight_color) !important; padding-bottom: 2px; margin-bottom: 8px; }
.px-4 { padding-lefT: 1rem; padding-right: 1rem; }
.py-6 { padding-bottom: 0; }
.overflow-hidden .flex .flex-col .relative col .gap-4 { min-width: calc(10px * var(--left_column)); max-width: calc(10px * var(--left_column)); } /* this is a problematic one */

/* automatic style classes */
.progressDiv .progress { background: var(--highlight_color); border-radius: 2px; }
.gallery-item { box-shadow: none !important; }

/* gradio elements overrides */
#txt2img_settings, #img2img_settings { min-width: calc(10px * var(--left_column)); max-width: calc(10px * var(--left_column)); }
#txt2img_prompt > label > textarea { font-size: calc(1.2rem / 50 * var(--font_scaler)); }
#txt2img_neg_prompt > label > textarea { font-size: calc(1.2rem / 50 * var(--font_scaler)); }
#img2img_prompt > label > textarea { font-size: calc(1.2rem / 50 * var(--font_scaler)); }
#img2img_neg_prompt > label > textarea { font-size: calc(1.2rem / 50 * var(--font_scaler)); }
#txt2img_generate, #img2img_generate, #txt2img_interrupt, #img2img_interrupt, #txt2img_skip, #img2img_skip { margin-top: 10px; min-height: 2rem; height: 63px; }
#txt2img_interrupt, #img2img_interrupt, #txt2img_skip, #img2img_skip { background-color: var(--inactive_color); }
#txt2img_gallery { background: black; }
#tab_extensions table { background-color: #222222; }
#style_pos_col, #style_neg_col, #roll_col { display: none; }
#interrogate_col { margin-top: 10px; }
#txt2img_progress_row > div { min-width: calc(10px * var(--left_column)); max-width: calc(10px * var(--left_column)); }
#save-animation { border-radius: 0 !important; margin-bottom: 16px; background-color: #111111; }
#open_folder { display: none }
```

**Comment by Gerschel** [comment]
Code to get the list of media queries, you might find handy after reading:

Gradio and some a1111 (depends on a1111 injection method)
```javascript
//Get stylesheets
let ss = gradioApp().styleSheets;
//Push Rules fom each into array
let ssArray = [];
[...ss].forEach( s => ssArray.push(Array.from(s.cssRules)));

//Flatten array
let s = ssArray.flat();

//Filter array for anything that has "@media" and print to console
s.filter( xx => xx.cssText.includes("@media")).forEach( m => console.log(m));
```

a1111 only
```javascript
// Get rules from html style tag, expand like array so flatten can work
let cssrules = [...gradioApp().querySelector("style").sheet.cssRules].flat()
cssrules.filter( cssr => cssr.cssText.includes("@media")).forEach( media => console.log(media))
```
.
.
.
Here's what I know, the buttons in the img2img settings area are defined using these tags, you can use the prefix "img2img_copy_to" to target them `[id^=img2img_copy_to]`. This prefix is auto-attached.
.
.
![image](https://user-images.githubusercontent.com/9631031/214756385-c10ac6ce-a1cd-45d5-9060-cd84655889f5.png)
.
.

```css
#img2img_copy_to_img2img, #img2img_copy_to_sketch, #img2img_copy_to_inpaint, #img2img_copy_to_inpaint_sketch,
```  
.
.
.
Next, they try to declare the img boxes to have a certain height in the code, but it doesn't work, I tested it.  
.
.
![image](https://user-images.githubusercontent.com/9631031/214756541-514dc0ba-8fbe-441e-ae6a-be086d0b5344.png)
.
.
So they workaround it in the css, but they don't just do the img component, they do every layer associated with it.  
.
.
![image](https://user-images.githubusercontent.com/9631031/214756706-359f9c9d-e45b-404c-b950-244fe0ba5243.png)
.
.
.

Here it is in a format that's easier to see the different targets:
```css
#img2img_image, 
#img2img_image > .h-60, 
#img2img_image > .h-60 > div, 
#img2img_image > .h-60 > div > img,
#img2img_sketch, 
#img2img_sketch > .h-60, 
#img2img_sketch > .h-60 > div, 
#img2img_sketch > .h-60 > div > img,
#img2maskimg, 
#img2maskimg > .h-60, 
#img2maskimg > .h-60 > div, 
#img2maskimg > .h-60 > div > img,
#inpaint_sketch, 
#inpaint_sketch > .h-60, 
#inpaint_sketch > .h-60 > div, 
#inpaint_sketch > .h-60 > div > img
{
    height: 480px !important;
    max-height: 480px !important;
    min-height: 480px !important;
}
```  
.
.
This is why you have the small image inside the larger one.  
.
.
.

Then, to address the grid for mobile, it would need to use media queries to establish different rules. Gradio is following a set common, which a1111 also follows ... mostly.  
.
.
.

For testing sizes, I recommend chrome browser developer edition, run in incognito so it doesn't cache, firefox has other handy tools too, so don't descriminate.  
https://www.google.com/chrome/dev/  

But you can keep your same workflow. I don't know how much extra it really offers. Either way, and you probably do this, you can toggle as if it's a mobile device, some things wont run like a mobile device until a browser refresh, like touch events for example.  

![image](https://user-images.githubusercontent.com/9631031/214757709-9dc14d26-35b6-45ab-ab1f-460f9bb0e77c.png)
.
.
.
.

This is all the media query sizes that gradio and a1111 uses, note that 767 with 768 is not needed if logic is done correctly:
.
.

![image](https://user-images.githubusercontent.com/9631031/214759043-3d39f1d4-946f-45fc-9448-0c019c77d86c.png)
.
.
.

```css
"(min-width: 640px)"
"(min-width: 768px)"
"(min-width: 1024px)"
"(min-width: 1280px)"
"(min-width: 1536px)"
"(min-width: 992px)"
"(min-width: 1200px)"
"screen and (min-width: 2500px)"
"screen and (min-width: 768px)"
"screen and (max-width: 767px)"
```  

More detail on a 'screen' max-width, now use the codes at the top to print them if you want to poke around:
![image](https://user-images.githubusercontent.com/9631031/214759608-4c056898-64a6-44f2-9e6f-a530a30ed535.png)
